### ISSUE TITLE
Writing unit tests for the bot

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#553]
The unit test branch coverage of our bot is currently 20% (30% including the test files). We would like to increase the test coverage of our bot to make one of our community's most essential tools more resilient to breakage. This *meta* issue contains information general information for this project and keeps track of the progress.

**Note:** If you want to help with writing unit tests, please make to get yourself assigned to one of the open issues for writing tests for an individual file. This system prevents that multiple people are working on the same tests.

## General information

We are using [`unittest`](https://docs.python.org/3.7/library/unittest.html) combined with [`coverage.py`](https://coverage.readthedocs.io/en/stable/) as the framework for our unit tests. To make sure you are using compatible versions of `unittest` and `coverage.py`, run your tests in the `pipenv` environment. Please note that our `bot` currently uses Python 3.7, which means that the new `unittest` features introduced in Python 3.8 are not yet available. 

A general introduction to writing tests for our bot is available in the [`README.md`](https://github.com/python-discord/bot/blob/master/tests/README.md) in the `/tests` directory of this repository. This file also contains information on how to run the test suite with `pipenv`.

A few important points:

- The `/tests/bot` directory uses the same directory structure as `/bot`. Please follow this convention to simplify locating the right tests.
- Make sure your tests do not rely on third-party connections or code external to the unit you are testing, but use mocks instead. See [README.md#mocking](https://github.com/python-discord/bot/blob/master/tests/README.md#mocking).
- Please take a look at the existing test files to get an idea of the existing conventions in this repository.
- The tests files themselves are considered to be part of the coverage. This makes sure that if certain tests are not discovered due to a mistake, this will show up in the coverage report for the relevant test files.
- If the code you're writing tests for does not lend itself well for unit tests (e.g., by containing monolithic functions), consider splitting the code up into smaller units to make it possible to test the different operations the code performs in an independent manner.

## Progress and links to issues for individual files

This directory tree keeps track of the files that are fully tested. Some files do already have test files associated with them, but do not yet have full coverage; for these partially covered files, I've indicated the current branch coverage percentage in parentheses.

- [ ] bot/
- [ ] ├── cogs/
- [ ] │   ├── moderation/
- [ ] │   │   ├── \_\_init\_\_.py (#556)
- [ ] │   │   ├── infractions.py (#558)
- [ ] │   │   ├── management.py (#559)
- [ ] │   │   ├── modlog.py (#560)
- [ ] │   │   ├── superstarify.py (#561)
- [ ] │   │   └── utils.py (#562)
- [x] │   ├── sync/
- [x] │   │   ├── \_\_init\_\_.py (#563)
- [x] │   │   ├── cog.py (#564)
- [x] │   │   └── syncers.py (#565)
- [x] │   ├── \_\_init\_\_.py
- [x] │   ├── antimalware.py (#555)
- [ ] │   ├── antispam.py (#570; current coverage: 35%)
- [ ] │   ├── clean.py (#572)
- [ ] │   ├── config\_verifier.py
- [ ] │   ├── defcon.py (#573)
- [x] │   ├── duck_pond.py (current coverage: 97%)
- [ ] │   ├── error\_handler.py (#575)
- [ ] │   ├── extensions.py (#577)
- [ ] │   ├── filtering.py (#578)
- [x] │   ├── jams.py (#582)
- [x] │   ├── logging.py (#583)
- [x] │   ├── security.py
- [x] │   ├── snekbox.py (#588)
- [ ] │   ├── tags.py (#589)
- [ ] │   ├── verification.py (#592)
- [x] ├── patches/
- [x] │   ├── \_\_init\_\_.py
- [x] ├── rules/
- [x] │   ├── \_\_init\_\_.py
- [x] │   ├── attachments.py
- [x] │   ├── burst.py (#595)
- [x] │   ├── burst\_shared.py (#596)
- [x] │   ├── chars.py (#597)
- [x] │   ├── discord\_emojis.py (#598)
- [x] │   ├── duplicates.py (#599)
- [x] │   ├── links.py (#600)
- [x] │   ├── mentions.py (#601)
- [x] │   ├── newlines.py (#602)
- [x] │   └── role\_mentions.py (#603)
- [ ] ├── utils/
- [x] │   ├── \_\_init\_\_.py (#604)
- [ ] │   ├── scheduling.py (#607)
- [x] │   └── time.py (#608; current coverage: 83%)

**Comment by MarkKoz** [comment]
For anyone that plans to work on this, I want to add that if you find something to be difficult to write tests for, consider how testable that code currently is. Ultimately, some things may need to just get restructured or rewritten in order to facilitate testing. This is especially true of monolithic functions - they could get split into smaller units. I think it can be quite easy to end up writing tests that are not really testing small enough units, so I want to emphasise that should be paid attention to.

**Comment by kwzrd** [comment]
I will try to help with this.

I'm cloning the repo for the first time so it will take me some time to familiarize myself with how things are done. Should I comment under specific issues and wait to get assigned, or should I just assign myself? I believe I do have the permissions, just not sure whether it's ok to do it without getting someone's approval first.

**Comment by scragly** [comment]
Self-assigning is a thing we should probably discuss a bit more amongst core developers to see what is best to do consistently in future and to use as a guideline for future contributors. For now, just leave a comment and leave the assigning to a core developer though to be safe.

I don't think you would, but try avoid taking on more than one issue at the same time if you feel tempted. Just comment on one, double checking that nobody is assigned yet beforehand, and then go crazy with that until you've got a functional PR. Once you're happy with that, move onto the next.

**Comment by kwzrd** [comment]
Understood and agreed.

**Comment by kwzrd** [comment]
Would it be reasonable to ask to be assigned for all the remaining rules?

#595 #596 #597 #598 #599 #602 #603

I've done #600 and #601 now and since they're all very similar, I think the remaining ones could go into a single PR so that it's easier to review as one batch. Would also be easier to work on for me. Let me know if that works.

**Comment by MarkKoz** [comment]
I'm OK with it.

**Comment by scragly** [comment]
@kwzrd they've now all been assigned. Thanks for jumping on them.

**Comment by MarkKoz** [comment]
The unit test issues are being closed because it is no longer a priority to increase coverage. There are more important issues to tackle.
